### ISSUE TITLE
No validation on some resources.

### ISSUE THREAD

**Issue by nikhgupta** [nikhgupta/whiplash_api#4]
API does not reject creation of objects without requisite fields.
This includes:

- creating items without titles
- creating orders without shipping info, or email
- orders/items can be created without providing any information, at all.
- `shipnotice_items` are not required for creating shipnotice (as against to what the docs say)

However, validations are checked correctly on the following resources:
- Shipment Notice (`shipnotice`)
- ShipnoticeItems

**Comment by ideaoforder** [comment]
Your observations here are correct, but the fix isn't a totally straightforward one on our end. I'll be working toward making those requirements work on our end, so there's no additional validation needed on your end. Once I put these updates in place, the correct errors will be returned. So you can mark this issue closed, since the shipnotice issue is already create.
